### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [uavster/mavwork#1]
Hi 
i am trying to build mavwork on pelican mastermind ubunto 12.04 ROS groovy

in step #3 for pelican in get th following error 

asctec@mastermind:~/rosbuild_ws/mavwork/proxies/Pelican/bin$ make

Compiling [/home/asctec/rosbuild_ws/mavwork/proxies/Pelican/bin/../sources/AltitudeSensor.cpp]...
In file included from /home/asctec/rosbuild_ws/mavwork/proxies/Pelican/bin/../sources/AltitudeSensor.cpp:20:0:
/home/asctec/rosbuild_ws/mavwork/proxies/Pelican/bin/../include/mav/pelican/AltitudeSensor.h:11:23: fatal error: phidget21.h: No such file or directory
compilation terminated.
make: **\* [AltitudeSensor.cppo] Error 1

Thanks 
Farhan

**Comment by uavster** [comment]
Hi Farhan,

Thanks for trying out mavwork. The proxy you are building was set for our
Pelican setup (
http://ignaciomellado.es/projects/MAVwork-support-for-the-Pelican-quadcopter ),
which had an analog ultrasound sensor for altitude measurement. The sensor
was connected to the USB port through a Phidget module that made de analog
to digital conversion. Installing the Phidget drivers should let the build
go on: http://www.phidgets.com/docs/Operating_System_Support . However, you
must replicate our hardware setup for it to work. If you prefer to install
your own one, you can modify the AltitudeSensor module in the proxy to suit
your needs. Hope this helps.

Kind regards,
Ignacio
